name: NPM Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v2.1.8
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: node_modules
        # An explicit key for restoring and saving the cache
        key: npm-${{ hashFiles('**/package-lock.json') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: npm

    - name: Build
      run: npm install

    - name: Debug
      run: |
        npm ls
        node -v

    - name: Run tests
      run: npm test
